openapi: 3.0.1
info:
  title: Agent Invocation API
  description: API to invoke Bedrock agent Lambda function
  version: 1.0.0

paths:
  /invoke-cloud-agent:
    post:
      summary: Invoke the Bedrock agent
      operationId: invokeCloudAgent
      parameters:
        - name: X-Session-Id
          in: header
          description: Optional session ID for the request
          required: false
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_input:
                  type: string
                  description: User input text (required)
                end_session:
                  type: boolean
                  description: Whether to end the session
              required:
                - user_input
      responses:
        '200':
          description: Successful response from agent
          headers:
            X-Session-Id:
              description: Bedrock session ID returned from the agent
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  agent_response:
                    type: string
                    description: The agent’s response text
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message